name: Generate Snake

on:
  schedule:
  
  
    - cron: "0 */12 * * *"
# "*/1 * * * *"
# cron(0/5
# "0 */1 * * *"


  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: MarceloZanguettin
          svg_out_path: dist/github-contribution-grid-snake.svg


      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
